version: '3'

volumes:
  bundle:
  mysql:

services:
  web:
    image: fmer/rails
    command: sh -c '(bin/bundle check || bin/bundle install) && bin/rails db:create && bin/rails s -b 0.0.0.0'
    environment:
      DATABASE_URL: mysql2://root:example@mysql/example_application
      REDIS_URL: redis://redis:6379/1
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src
      - bundle:/usr/local/bundle
    tmpfs:
      - /usr/src/tmp
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:4
