version: '3'

volumes:
  bundle:
  mysql:

services:
  web:
    image: fmer/rails
    command: bin/rails s -b 0.0.0.0
    environment:
      DATABASE_URL: mysql2://root:example@mysql/example_application
      REDIS_URL: redis://redis:6379/1
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src
      - bundle:/usr/local/bundle
    tmpfs:
      - /usr/src/tmp
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
