development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: src_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: src_production
